app-id: "{APP_ID}"
runtime: org.kde.Platform
runtime-version: "5.15-22.08"
sdk: org.kde.Sdk
command: "{APP_MODULE}"
finish-args:
# OpenGL
- "--device=dri"
# GUI
- "--share=ipc"
- "--socket=x11"
# Sound
- "--socket=pulseaudio"
# Files & network
- "--share=network"
- "--filesystem=host"
- "--filesystem=xdg-run/gvfs"
# Screen inhibit
- "--talk-name=org.freedesktop.ScreenSaver"
# Can't use Wayland
- "--env=QT_QPA_PLATFORM=xcb"
# Disable annoying warnings
# Qt: Session managment error: Could not open network socket
# https://stackoverflow.com/questions/986964/qt-session-management-error
- "--env=SESSION_MANAGER="

cleanup:
- "/include"
- "/lib/*.a"
- "/lib/*.la"
- "/lib/debug"
- "/lib/pkgconfig"
- "/share/man"

modules:
- libvlc.yml
- pyqt.yml
- dependencies.yml
